#!/usr/bin/env python3
"""Generate golden satellite test vectors for test/satellite_vectors.h.

Satellites are exchanged as CelesTrak OMM CSV (the TLE format cannot carry the
6-digit catalog numbers issued since July 2026). This script freezes a set of
element sets, writes each as a CelesTrak-style CSV row, and records what the
reference implementations compute *from that same text*:

  * python-sgp4 (MIT; wraps David Vallado's C++ SGP4) for TEME position and
    velocity, including the near-Earth cases of Vallado's verification file
    SGP4-VER.TLE, which ships inside the python-sgp4 package;
  * Skyfield for observer altitude/azimuth and for rise/culminate/set events.

Regenerate (versions are recorded in the header):

    python3 -m venv .venv && .venv/bin/pip install sgp4 skyfield
    .venv/bin/python scripts/gen_sgp4_vectors.py > test/satellite_vectors.h
"""

import math
import os
import sys
from datetime import datetime, timedelta, timezone

import sgp4
import skyfield
from sgp4 import omm
from sgp4.api import Satrec
from skyfield.api import EarthSatellite, load, wgs84

CSV_HEADER = (
    "OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,"
    "ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,"
    "ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT"
)

# Frozen element sets (fetched from CelesTrak on 2026-09-24)
TLES = [
    (
        "ISS (ZARYA)",
        "1 25544U 98067A   26267.14191496  .00009634  00000+0  18116-3 0  9999",
        "2 25544  51.6318 170.3464 0004691 174.6338 185.4701 15.49258637587098",
    ),
    (
        "STARLINK-1008",
        "1 44714U 19074B   26266.77099548  .00032794  00000+0  32822-3 0  9996",
        "2 44714  53.1462 310.9835 0002568  68.1953 291.9336 15.65286625379586",
    ),
    (
        "CSS (TIANHE)",
        "1 48274U 21035A   26267.18690940  .00017686  00000+0  21417-3 0  9991",
        "2 48274  41.4677  80.8645 0002286 304.1802  55.8820 15.60246980308621",
    ),
    # Decaying, perigee ~171 km: simplified-drag branch
    (
        "STARLINK-3069",
        "1 49176U 21082AY  26267.49266630  .03370800  43377-5  46196-3 0  9998",
        "2 49176  69.9854  88.1606 0009771 277.1217  82.8900 16.34827812277353",
    ),
]

# A real CelesTrak CSV row with a 6-digit catalog number (not representable as TLE)
CSV_ROWS = [
    "JAMX01 (JING'AN DREAM STAR),2026-195A,2026-09-24T06:48:06.955776,15.09434944,.00139726,97.5380,"
    "340.5763,149.8351,210.3686,0,U,100465,999,454,.27596078E-3,.4361E-4,0",
]

TSINCE = [-4320.0, -1440.0, -90.0, 0.0, 1.0, 10.0, 90.0, 360.0, 1440.0, 4320.0]

OBS_LAT, OBS_LON = 59.32938, 18.06871  # Stockholm, sea level

J2000_UTC = datetime(2000, 1, 1, 12, 0, 0, tzinfo=timezone.utc)


def csv_row(sat, name):
    """Format a satrec as a CelesTrak OMM CSV row, with CelesTrak's precision."""
    epoch = J2000_UTC + timedelta(days=(sat.jdsatepoch - 2451545.0) + sat.jdsatepochF)
    deg = 180.0 / math.pi
    return ",".join(
        [
            name,
            "UNKNOWN",
            epoch.strftime("%Y-%m-%dT%H:%M:%S.%f"),
            f"{sat.no_kozai * 720.0 / math.pi:.8f}",
            f"{sat.ecco:.7f}".lstrip("0"),
            f"{sat.inclo * deg:.4f}",
            f"{sat.nodeo * deg:.4f}",
            f"{sat.argpo * deg:.4f}",
            f"{sat.mo * deg:.4f}",
            "0",
            "U",
            str(sat.satnum),
            "999",
            "0",
            f"{sat.bstar:.8E}",
            "0",
            "0",
        ]
    )


def satrec_from_csv(row):
    fields = dict(zip(CSV_HEADER.split(","), row.split(",")))
    sat = Satrec()
    omm.initialize(sat, fields)
    return sat


def jd_to_time(ts, jd):
    return ts.from_datetime(J2000_UTC + timedelta(days=jd - 2451545.0))


def vallado_near_earth():
    """Near-Earth cases from Vallado's verification file shipped with python-sgp4."""
    path = os.path.join(os.path.dirname(sgp4.__file__), "SGP4-VER.TLE")
    lines = [ln.rstrip("\n") for ln in open(path) if not ln.startswith("#")]
    cases = []
    for l1, l2 in zip(lines[::2], lines[1::2]):
        sat = Satrec.twoline2rv(l1[:69], l2[:69])
        if 2 * math.pi / sat.no_kozai >= 225.0:
            continue  # deep space: SDP4, unsupported
        start, stop, step = (float(x) for x in l2[69:].split())
        n = max(1, int((stop - start) / step))
        times = sorted({start, stop} | {start + step * k for k in range(0, n + 1, max(1, n // 6))})
        cases.append((csv_row(sat, f"VALLADO {l1[2:7].strip()}"), times))
    return cases


def main():
    cases = [(csv_row(Satrec.twoline2rv(l1, l2), name), TSINCE) for name, l1, l2 in TLES]
    cases += [(row, TSINCE) for row in CSV_ROWS]
    cases += vallado_near_earth()

    out = sys.stdout
    out.write("/* Generated by scripts/gen_sgp4_vectors.py: do not edit by hand.\n")
    out.write(f" * python-sgp4 {sgp4.__version__} (opsmode 'i', WGS-72), Skyfield {skyfield.__version__}\n */\n\n")
    out.write("#ifndef SATELLITE_VECTORS_H\n#define SATELLITE_VECTORS_H\n\n// clang-format off\n\n")
    out.write(f'static const char *omm_csv_header = "{CSV_HEADER}";\n\n')

    out.write("struct OmmCase\n{\n    const char *row;\n    int catnr;\n    double epoch_jd;\n};\n\n")
    out.write("static const struct OmmCase omm_cases[] = {\n")
    for row, _ in cases:
        sat = satrec_from_csv(row)
        esc = row.replace("\\", "\\\\").replace('"', '\\"')
        out.write(f'    {{"{esc}", {sat.satnum}, {sat.jdsatepoch + sat.jdsatepochF:.10f}}},\n')
    out.write("};\n\n")

    out.write("struct PropCase\n{\n    int sat;\n    double tsince;\n    int error;\n")
    out.write("    double r[3];\n    double v[3];\n};\n\n")
    out.write("static const struct PropCase prop_cases[] = {\n")
    for i, (row, times) in enumerate(cases):
        sat = satrec_from_csv(row)
        for t in times:
            e, r, v = sat.sgp4_tsince(t)
            if (e != 0 and e != 6) or any(math.isnan(x) for x in r):
                out.write(f"    {{{i}, {t!r}, {e}, {{0, 0, 0}}, {{0, 0, 0}}}},\n")
                continue
            rs = ", ".join(f"{x:.9f}" for x in r)
            vs = ", ".join(f"{x:.12f}" for x in v)
            out.write(f"    {{{i}, {t!r}, {e}, {{{rs}}}, {{{vs}}}}},\n")
    out.write("};\n\n")

    ts = load.timescale()
    obs = wgs84.latlon(OBS_LAT, OBS_LON, elevation_m=0.0)
    out.write(f"static const double obs_lat_deg = {OBS_LAT};\nstatic const double obs_lon_deg = {OBS_LON};\n\n")

    # Topocentric altitude/azimuth (azimuth from North through East)
    out.write("struct TopoCase\n{\n    int sat;\n    double jd_utc;\n    double alt_deg;\n    double az_deg;\n};\n\n")
    out.write("static const struct TopoCase topo_cases[] = {\n")
    for i in range(3):
        sat = satrec_from_csv(cases[i][0])
        es = EarthSatellite.from_satrec(sat, ts)
        epoch = sat.jdsatepoch + sat.jdsatepochF
        above, below = [], []
        jd = epoch
        while jd < epoch + 1.0 and (len(above) < 6 or len(below) < 2):
            alt, az, _ = (es - obs).at(jd_to_time(ts, jd)).altaz()
            if alt.degrees > 5.0 and len(above) < 6:
                above.append((jd, alt.degrees, az.degrees))
                jd += 90.0 / 86400.0
            elif alt.degrees < -20.0 and len(below) < 2:
                below.append((jd, alt.degrees, az.degrees))
                jd += 3600.0 / 86400.0
            else:
                jd += 20.0 / 86400.0
        for jd, alt, az in above + below:
            out.write(f"    {{{i}, {jd:.10f}, {alt:.6f}, {az:.6f}}},\n")
    out.write("};\n\n")

    # Geometric ISS passes above 10 degrees over the three days after epoch
    out.write("struct PassCase\n{\n    double rise_jd;\n    double culminate_jd;\n    double culminate_alt_deg;\n")
    out.write("    double set_jd;\n};\n\n")
    out.write("static const struct PassCase iss_passes[] = {\n")
    sat = satrec_from_csv(cases[0][0])
    es = EarthSatellite.from_satrec(sat, ts)
    epoch = sat.jdsatepoch + sat.jdsatepochF
    times, events = es.find_events(obs, jd_to_time(ts, epoch), jd_to_time(ts, epoch + 3.0), altitude_degrees=10.0)
    current = {}
    for t, ev in zip(times, events):
        jd = (t.utc_datetime() - J2000_UTC).total_seconds() / 86400.0 + 2451545.0
        if ev == 0:
            current = {"rise": jd}
        elif ev == 1 and "rise" in current:
            current["cul"] = jd
            current["alt"] = (es - obs).at(t).altaz()[0].degrees
        elif ev == 2 and "cul" in current:
            out.write(f"    {{{current['rise']:.10f}, {current['cul']:.10f}, {current['alt']:.4f}, {jd:.10f}}},\n")
            current = {}
    out.write("};\n\n// clang-format on\n\n#endif // SATELLITE_VECTORS_H\n")


if __name__ == "__main__":
    main()
